trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  javaVersion: '17'
  mavenVersion: '3.8.4'
  projectName: 'CP-Spring-Initializr'
  goals: 'initialize release:clean release:prepare --batch-mode release:perform -Pcloud'
  jobDisplayName: 'Maven release plugin'

steps:
- checkout: self
  clean: true
  persistCredentials: true

- task: DownloadSecureFile@1
  name: key
  displayName: 'Download GPG'
  inputs:
    secureFile: 'key.asc'
- task: CmdLine@2
  displayName: Import gpg
  inputs:
    script: |
      gpg --import $(key.secureFilePath)      

- task: DownloadSecureFile@1
  name: settings
  displayName: 'Download settings.xml'
  inputs:
    secureFile: 'settings.xml'
  
- task: Maven@3
  displayName: $(jobDisplayName)
  inputs:
    mavenPomFile: 'lib/pom.xml'
    goals: $(goals)
    options: '--settings $(settings.secureFilePath) -Duser_name=$(username) -Duser_password=$(System.AccessToken)'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
