trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  javaVersion: '17'
  mavenVersion: '3.8.4'
  projectName: 'CP-Spring-Initializr'
  goals: 'initialize release:clean release:prepare --batch-mode release:perform -Pcloud'
  jobDisplayName: 'Maven release plugin'

steps:
- checkout: self
  clean: true
  persistCredentials: true

- task: DownloadSecureFile@1
  name: key
  displayName: 'Download GPG'
  inputs:
    secureFile: 'key.asc'
- task: CmdLine@2
  displayName: Import gpg
  inputs:
    script: |
      gpg --import $(key.secureFilePath)      

- task: DownloadSecureFile@1
  name: settings
  displayName: 'Download settings.xml'
  inputs:
    secureFile: 'settings.xml'
  
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Extracting version from pom.xml"
      VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      echo "##vso[task.setvariable variable=version]v$VERSION"

- task: Maven@3
  displayName: $(jobDisplayName)
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean deploy -Pcloud'
    options: '--settings $(settings.secureFilePath)'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- script: |
    find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'
  displayName: 'List files in working directory'


- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github-dobry-serviceconnection'
    repositoryName: 'cleverpine/cp-spring-initializr'
    action: 'create'
    tagSource: 'userSpecifiedTag'
    tag: '$(version)' # or a specific tag like 'v1.0'
    releaseTitle: 'Release $(tag)'
    assets: |
      $(System.DefaultWorkingDirectory)/target/*.jar
      $(Build.ArtifactStagingDirectory)/*.zip
    assetUploadMode: 'delete'
    isDraft: false
    isPreRelease: false
    releaseNotesSource: 'inline'
    releaseNotes: 'Release notes for version $(tag)'

