spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
initializr:
  group-id:
    value: com.cleverpine
  version:
    value: 0.0.1-SNAPSHOT
  javaVersions:
    - id: 17
      default: true
  languages:
    - name: Java
      id: java
      default: true
  packagings:
    - name: Jar
      id: jar
      default: true
  bootVersions:
    - name: 3.2.0
      id: 3.2.0
      default: true
  dependencies:
    - name: CleverPine
      content:
        - name: CleverPine Logging Library
          id: cp-logging-library
          groupId: com.cleverpine
          artifactId: cp-logging-library
          description: CleverPine Logging Library
          mappings:
            - version: 1.0.9
              compatibilityRange: "3.1.5"
          starter: true
        - name: CleverPine Virava Spring Helper
          id: cp-virava-spring-helper
          groupId: com.cleverpine
          artifactId: cp-virava-spring-helper
          description: CleverPine Virava Spring Helper
          mappings:
              - version: 3.1.3
                compatibilityRange: "3.1.5"
          starter: false
        - name: CleverPine JPA Specification Resolver
          id: cp-jpa-specification-resolver
          groupId: com.cleverpine
          artifactId: cp-jpa-specification-resolver
          description: CleverPine JPA Specification Resolver
          mappings:
              - version: 1.0.0
                compatibilityRange: "3.1.5"
          starter: false
        - name: CleverPine Spring Error util
          id: cp-spring-error-util
          groupId: com.cleverpine
          artifactId: cp-spring-error-util
          description: CleverPine Spring Error util
          mappings:
              - version: 2.0.1
                compatibilityRange: "3.1.5"
          starter: false
    - name: Spring framework
      content:
        - name: Spring AOP
          id: aop
          description: Aspect-Oriented Programming with Spring AOP and AspectJ.
          scope: provided
          starter: false
        - name: Log4j2
          id: log4j2
          description: Log4j2 logging framework.
          starter: false
        - name: Web
          id: web
          description: Servlet web application with Spring MVC and Tomcat
          starter: false
        - name: Spring Security
          id: security
          description: Highly customizable authentication and access-control framework for Spring applications.
          starter: false
    - name: Developer Tools
      content:
        - name: Lombok
          id: lombok
          groupId: org.projectlombok
          artifactId: lombok
          scope: annotationProcessor
          description: Java annotation library which helps to reduce boilerplate code.
          mappings:
            - version: 1.18.30
              compatibilityRange: "3.1.5"
          starter: false
        - name: Jackson databind
          id: jackson-databind-nullable
          groupId: org.openapitools
          artifactId: jackson-databind-nullable
          description: JsonNullable wrapper class and Jackson module to support fields with meaningful null values.
          mappings:
            - version: 0.2.6
              compatibilityRange: "3.1.5"
          starter: false
        - name: OpenAPI Codegen Plugin
          id: openapi-generator-maven-plugin
          groupId: org.openapitools
          artifactId: openapi-generator-maven-plugin
          description: OpenAPI Codegen Plugin
          mappings:
            - version: 7.2.0
              compatibilityRange: "3.1.5"
          starter: false